<?xml version="1.0" encoding="utf-8"?><Database Name="login_db" Class="newDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC\SQLEXPRESS;Initial Catalog=login_db;Integrated Security=True" SettingsObjectName="AdminLogin.Properties.Settings" SettingsPropertyName="login_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.login_info" Member="login_infos">
    <Type Name="login_info">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.acc_type" Method="acc_type">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pro_login" Method="pro_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="pro_loginResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>